"""Mesh generation stage: strategy chain + fallback orchestration.

Walks the mode's backend chain from ``config.yaml`` (``modes.<mode>``) and
runs backends in order. The first success wins and is recorded in the report;
every failure is logged with its reason. If everything fails, the stage
raises a StageError so the report shows a failed stage — never a silent gap.

Chain mapping (mode strategies -> backends):
    capture    -> [colmap]
    generative -> [triposr, stable_fast_3d]
    depth_relief -> [depth_relief]
"""

from __future__ import annotations

from pathlib import Path

from core.logging import get_logger
from core.model_manager import free_memory
from core.pipeline import RunContext, StageError, StageResult

log = get_logger("generate")

STRATEGY_BACKENDS = {
    "capture": ["colmap"],
    "generative": ["triposr", "stable_fast_3d"],
    "depth_relief": ["depth_relief"],
}


def _backend_for(name: str, cfg):
    if name == "triposr":
        from adapters.generative.triposr_adapter import TripoSRBackend
        return TripoSRBackend(cfg)
    if name == "stable_fast_3d":
        from adapters.generative.stable_fast_3d_adapter import StableFast3DBackend
        return StableFast3DBackend(cfg)
    if name == "depth_relief":
        from scripts.generate.generate_depth_relief import DepthReliefBackend
        return DepthReliefBackend(cfg)
    if name == "colmap":
        from adapters.capture.colmap_adapter import ColmapBackend
        return ColmapBackend(cfg)
    raise KeyError(f"unknown backend '{name}'")


def run_generate(ctx: RunContext) -> StageResult:
    frames: list[Path] = ctx.shared("preprocessed_frames", []) or []
    if not frames:
        raise StageError("generate_mesh: no preprocessed frames from ingest stage")

    chain = ctx.cfg.mode_chain(ctx.mode)
    attempts: list[dict] = []
    out_path = ctx.job.raw_obj_path

    for strategy in chain:
        for backend_name in STRATEGY_BACKENDS.get(strategy, []):
            ctx.progress.emit("generate_mesh", "progress",
                              f"trying backend '{backend_name}'", 0.2)
            backend = _backend_for(backend_name, ctx.cfg)
            if not backend.available():
                log.info("backend '%s' unavailable, skipping", backend_name)
                attempts.append({"backend": backend_name, "status": "skipped",
                                 "error": "missing weights/binary"})
                continue

            result = backend.run(ctx, frames, out_path)
            attempts.append({
                "backend": backend_name,
                "status": "success" if result.success else "failed",
                "error": result.error,
                "duration_s": result.duration_s,
                "settings": result.settings,
            })
            free_memory()
            if result.success:
                log.info("mesh generated by '%s' in %.1fs -> %s",
                         backend_name, result.duration_s, out_path)
                ctx.progress.emit("generate_mesh", "finished",
                                  f"backend '{backend_name}' succeeded", 1.0)
                # raw GLB preview for the GUI + downstream stages
                _write_glb_preview(out_path, ctx.job.raw_glb_path)
                return StageResult(
                    status="success",
                    fallback_used=backend_name,
                    artifacts={
                        "backend": backend_name,
                        "attempts": attempts,
                        "raw_mesh": str(out_path),
                        "duration_s": result.duration_s,
                    },
                )
            log.warning("backend '%s' failed: %s", backend_name, result.error)

    raise StageError(
        f"all mesh backends failed for mode '{ctx.mode}': "
        + "; ".join(f"{a['backend']}={a['error'] or a['status']}" for a in attempts)
    )


def _write_glb_preview(obj_path: Path, glb_path: Path) -> None:
    try:
        import trimesh

        mesh = trimesh.load(obj_path)
        glb_path.parent.mkdir(parents=True, exist_ok=True)
        mesh.export(glb_path)
        log.info("glb preview written: %s", glb_path)
    except Exception as exc:  # noqa: BLE001 - preview is optional
        log.warning("could not write glb preview: %s", exc)
